// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywpcsubtzueukpnullro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3cGNzdWJ0enVldWtwbnVsbHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjI2MjcsImV4cCI6MjA3NDAzODYyN30.n3V_y4tjK6id87ogH54ZGCJjQqUghZB9Kzmg9HKG3Ss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});